
platform :ios, '7.0'

target 'MCS' do
pod 'AFNetworking','3.1.0'
pod 'Masonry', '~> 1.0.1'
pod 'LKDBHelper', '2.3.1'
pod 'MBProgressHUD', '0.9.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'ReactiveCocoa', '2.5'
pod 'WebViewJavascriptBridge', '~> 5.0.5'


end
